version: "3"
services:
  backend:
    build:
      context: ./back
    ports:
      - "4000:4000" # Map container port 3000 to host port 3000
    depends_on:
      - frontend

  frontend:
    build:
      context: ./FRONT
    ports:
      - "8000:8000" # Map container port 8080 to host port 8080
